blog/urls.py
from django.conf.urls import url
from django.urls import path
from blog.views import *
from . import views

app_name = 'blog' #루트 url에서 namespace로 지정한 이름. 꼭 써줘야 defualt url이 됨

urlpatterns =[
    url(r'^$', PostLV.as_view(), name='index'),
    # /. blog/에서 blog는 namespace에서 지정한 부분
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    #위와 동일. 패턴명만 다름
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    #\w는 문자+숫자. '-'가들어간 문자숫자가 하나이상. ex. post/django-example/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    # ex. archive/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    # ex. 2012/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    # ex. 2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(),
        name='post_day_archive'),
    # ex. 2012/nov/10/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    # ex. today/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
    # ex. tag/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    # ex. tag/tagname/
    #[^/]+ : /이외의 문자가 하나이상 있다. (?u)앞의 구문을 유니코드로 인식해라(한글이 와도 인식되도록)
    url(r'^search/$', SearchFormView.as_view(), name='search'),
    #폼을 보여주고 폼에있는 데이터를 처리하기 위해 FormView를 상속받아 정의
    #blog/search/
    path('add/', views.PostCreateView.as_view(), name='add'),  # /Post/add/
    path('change/', views.PostChangeLV.as_view(), name='change'),  # /Post/change/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),  # /Post/99/update/
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),  # /Post/99/delete/
    # url()은 re_url로 대체. views.뷰클래스명.as_view()쓰는 패턴에 유의

]

bookmark/urls.py
from django.conf.urls import url
from django.urls import path, re_path
#일반적인 패턴은 path, 복잡한 정규식을 써야할 땐 re_path를 사용
from bookmark.views import BookmarkDV, BookmarkLV
from . import views #path를 쓸때는 이구문을 반드시 넣어야 함

app_name = 'bookmark' #루트 url에서 namespace로 지정한 부분. 이 부분이 default url이 됨

urlpatterns = [
    url(r'^$', BookmarkLV.as_view(), name='index'), #/bookmark/
                                                    #이 패턴의 이름은 bookmark:index가 됨
    url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'), #ex. /bookmark/1/
                                                    #이 패턴의 이름은 bookmark:detail이 됨
    path('add/', views.BookmarkCreateView.as_view(), name='add'), #/bookmark/add/
    path('change/', views.BookmarkChangeLV.as_view(), name='change'), #/bookmark/change/
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'), #/bookmark/99/update/
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'), #/bookmark/99/delete/
    #url()은 re_url로 대체. views.뷰클래스명.as_view()쓰는 패턴에 유의
]

mainsite/urls.py
# url()와 path()의 차이
# path가 개선된 버전으로 사용 문법이 url에 비해 간략화 됨
# url(r'^book/(?P<pk>/d+)/$', views.book_detail)이
# path(r'^book/<int:pk>/', views.book_detail)로 바뀌어 간단하게 표현할 수 있음

from django.contrib import admin #기본적으로 로딩. admin싸이트 접속용도
from django.urls import path #기본적으로 로딩. path를 통해 보통은 접근
from django.conf.urls import url, include #보통 프로젝트용 url과 앱용 url 두개가 있으나, 여기선 프로젝트용
                                 #하나로만 바로 conf할꺼라 필요

from django.conf.urls.static import static #정적파일을 처리하는 뷰를 호출하도록 그에맞는 url패턴 반환
from django.conf import settings #settings변수 호출. setting.py에서 정의한 객체들을 담고 있음

# from bookmark.views import BookmarkLV, BookmarkDV
#view에서 정의한 클래스뷰들을 불러와서 url로 링크시켜야 해당 요구가 들어왔을때 링크해 줌

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from mainsite.views import HomeView #대문싸이트를 만들기 위한 view
from mainsite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls), #장고 conf파일의 url함수는 내부적으로 re모듈을 호출하는 듯.
                                      #url()의 첫번째 변수가 regex 즉 정규식임
                                      #여기서 바로 정규식을 사용함. ^ ~로 시작하는.

    #인증관련 처리 URL
    url(r'^accounts/', include('django.contrib.auth.urls')),
    #django.co~는 장고가 기본적으로 제공하는 인증관련 앱으로, url과 템플릿파일명이 지정되어 있다. 책236페이지 표 참조
    #로그인/아웃 관련 url과 view는 장고가 제공하나 해당 템플릿은 직접 만들어야 한다. 물론 템플릿명도 지정됨.
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),  #계정 생성처리를 하는 url
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'), #생성 완료를 보여주는 url

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')), #include 함수도 import해야함
    #최근에 url()대신해 path()가 소개됨. 해당 url이 들어오면 bookmark앱의 urls파일로 가서 처리해라
    #차이는 url에서 id를 추출하는 방식이 간편해짐. url은 ?<~~>였는데 path는(<int:number>형식)으로 간단해짐
    url(r'^blog/', include('blog.urls', namespace='blog')), #include 함수도 import해야함
    url(r'^photo/', include('photo.urls', namespace='photo')),
    #url(r'^photo/', ListView.as_view(model=Album), name='album_list'),로 한번에 할 수도 있음

##bookmark를 단독으로 urlconf할때 썻던 코드
    # #Class-based view for bookmark 앱
    # url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),# xx$ xx로 끝나야함
    # #원래는 view.view처리함수 형태가 되어야 하나, 장고의 제네릭(표준)뷰를 쓰기 위해 as_view 사용
    # #name은 이 url패턴을 뭐라고 부를 것인가를 정의하는 것
    # url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
    # #bookmark/11~/형태의 url. ?p<>는 정규식 그룹명을 지정한 것. 뷰를 호출할 때 primary key가
    # #변수로 같이 넘겨짐. views.detal(request, pk)처럼.
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #개발과정에서 미디어파일을 처리하기 위해 추가
#statc(css, js같은 정적인 파일들)파일을 처리하는 url_conf를 추가(왜 쓰는지는 루트폴더에 작성해놓은 '장고 정적서비스 개념잡기 참조'
#static(prefix, view=django.views.static.serve, **kwarg)가 원래 용법
#즉, setting.py에서 MEDIA_URL로 지정한 url('/static/')이 들어오면 django.views.static~~이란
#뷰가 처리하고, 인수로 MEDIA_ROOT(os.path.join(BASE_DIR, 'media'))를 넘겨줘라 라는 것
#view는 장고가 제공하는 view니까 따로 코딩하지 않는 듯.

# static()함수의 다른 설명
# 정적 파일에 접근할 URL 접두사(staticfiles)를 첫 번째 인자로 넣고 정적 파일이 위치한 경로를 document_root라는 키워드 인자로 전달하면,
# 이런 내용을 django.views.static.serve라는 뷰 함수가 사용합니다. 이 serve 함수는 서버에 위치한 파일을 읽어서(open(fullpath, 'rb'))
# 스트리밍 방식으로 응답(StreamingHttpResponse)합니다. 실제 파일 서빙을 하는 것입니다. 물론 성능은 웹 서버가 직접 서빙하는 것보다 떨어지므로
# 개발 단계에서만 쓰는 게 좋을텐데, django.conf.urls.static의 static 함수는 settings의 DEBUG가 True인 경우에만 이런 정적 파일 제공에
# 필요한 URL 패턴을 만듭니다. 간단히 말해서 DEBUG=True인 경우에만 static 함수는 우리가 원하고 기대하는 동작을 합니다.

bookmark/models.py
from __future__ import unicode_literals #python 2.X 호완용
from six import python_2_unicode_compatible #python2.x대의 문자열 처리 방식을 3.x대로 바꿔주는 것
# from django.utils.encoding import python_2_unicode_compatible에서 장고 3.0.4부터 바뀜

from django.db import models
#1새로운 DB를 만들려면 모델에 클래스를 만들고, 이를 admin사이트에 등록해야함
#2 manage.py파일을 이용해 makemigrations 실행, 변경사항 파일을 만들고, migrate로 이를 적용시킴
from django.contrib.auth.models import User

@python_2_unicode_compatible #함수를 인자로 갖는 또다른 함수(혹은 클래스)
#데코레이터. 파이썬이 함수를 또다른 함수의 '인자'로 쓸수 있다는 특징 활용(1st citizen class).
#@데코함수명, 바로 아래의 '다른 함수(클래스)'를 그대로 포장해서(wrap) 데코함수로 돌려주면, 데코함수에서는
#'다른 함수'앞(뒤)에 추가적인 작업을 한 후 전체 값을 돌려준다. 즉 다른 함수를 바꾸지 않고 추가적인 작업 수행
#즉 재활용하고픈 함수는 '다른 함수'이고, 추가하고픈 내용이 '데코 함수'이다.
class Bookmark(models.Model): #데이터베이스를 지칭하는 클래스. 장고의 Model클래스를 상속받아 간단히 처리.
    title = models.CharField(max_length=100, blank=True, null=True)#title이라는 칼럼만들기
    #blank=True이면 empty value 허용. null=true면 DB의 빈칸에 null이라고 입력.
    #옵션에 db_column값을 않넣으면 컬럼명에 변수명이 자동으로 들어감
    url = models.URLField('url', unique=True) #컬럼의 별칭 'url'(Field.verbose_name).
    # url은 단 하나만 있어야 하므로 unique를 True로
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE, blank=True)
    #bookmark의 생성은 로그인 회원만 할 수 있도록 하기 위해, User테이블을 가져와 참조키롤 설정
    #기존에 만든 콘텐츠는 값이 null이므로 null을 True해놔야 함. 사용자가 지워지면 해당 bookmark가
    #따라서 지워지도록 on_delete항목을 CASCADE로 설정(필수). 따라지워지지 않으려면 PROTECT하면 됨

    def __str__(self): #admin사이트나 장고쉘에서 모델(테이블)의 개별 객체(row요소)를 표시할 때, '이것은
                   #어떤 객체다'라고 표시할 필요가 있는데(제목줄에 객체값을 쓰고, 아래 변경항목 나타낼 때)
                   #대표적으로 뭐라고 쓸 것인가를 결정. (__str__)을 적용, 이를 문자로 나타내 줌
        return self.title #어디서든 Bookmark테이블의 객체를 호출하면 그 객체의 타이틀값을 대표로 나타내라.
        #return '%s %s' %(self.title, self.url) #이면 객체를 불렀을 때 둘의 이름이 다 나올 것

bookmark/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
#reverse()함수를 쓰려면 url.py가 메모리에 로딩되어야 하는데, view처리 단계에서 로딩되지 않을수도
#있으므로 reverse_lazy함수를 썼다고 함
from django.contrib.auth.mixins import LoginRequiredMixin
from mainsite.views import OwnerOnlyMixin
#@login_required()데코레이터 기능을 클래스에 적용 시 사용한다고 함

#----list view : 북마크 테이블의 레코드리스트를 보여주라는 처리방식
class BookmarkLV(ListView): #장고의 표준양식을 상속받아서 간단하게 리스트 표출
    model = Bookmark #상속받았을때 필수적으로 넣어야 함.
    ''' 함수형 뷰였을 경우에는 첫째, DB에서 쿼리를 통해 데이터를 가져와 객체1을 만들고
    둘째, 딕셔너리 형태로 템플릿에서 사용하게 컨텍스트 변수(변수명:객체1 형식)를 만들고
    셋째, render함수로 지정된 템플릿파일에 컨텍스트 변수를 적용시킨 HTML텍스트를 만들어서
    넷째, 역시 render함수가 이를 HttpResponse객체에 담아 반환하는 작업을 한다. 
    
    제네릭 뷰가 이같은 과정을 축약해 위처럼 한줄의 코드로 만들어 버린것. 곧 자동으로 컨텍스트 변수는
    object_list로, 템플릿파일은 모델명소문자_list.html(bookmark_list.html)로 지정된다.
    '''

#----Detail view : 북마크 테이블의 특정 레코드에 대한 상세정보를 보여주라는 처리방식
class BookmarkDV(DetailView): #장고의 표준양식을 상속받아서 간단하게 리스트 표출
    model = Bookmark
    ''' 마찬가지로 컨텍스트 변수는 object로 템플릿파일은 모델명소문자_detail.html로 자동 지정됨
    테이블에서 특정 객체를 가져오는 경우는(pk를 지정해서 호출할 경우) urlconf에서 넘어옴
    '''

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    #LoginRe~~를 상속받는 클래스는 로그인된 경우에만 접근 가능. 로그인 되지 않은 상태에서 B~CreateView를
    #호출하면 로그인 페이지로 이동시킨다.
    #Createview를 상속받으면 아래 항목만 채워주면 적절한 폼을 보여주고, form에 입력된 내용에서 에러가 없으면
    #입력된 내용으로 테이블에 레코드를 생성한다.
    model = Bookmark #CreateView 기능을 적용할 테이블
    fields = ['title', 'url'] #CreateView의 기능에 따라 폼을 보여줄때, title과 url입력폼을 보여줌
    success_url = reverse_lazy('bookmark:index')#레코드 생성이 완료되었을때 이동할 url

    #데코레이터처럼 부모클래스의 메소드를 호출하기 전에 내용을 추가하고 싶을때, 이런식으로
    # 같은 이름으로 재정의 하는 듯. 결론은 부모클래스의 같은 메소드를 호출하게 됨.
    def form_valid(self, form): #form_vaild의 재정의. owner항목에 user의 이름을 넣기 위해.
        form.instance.owner = self.request.user
        #form의 owner필드에 로그인된 user객체를 할당
        return super(BookmarkCreateView, self).form_valid(form)
    #제출된 form의 유효성 검사를 마친 후 이상이 없으면 form_valid메소드를 호출 함(CreateView의 자동 기능)

class BookmarkChangeLV(LoginRequiredMixin, ListView): #리스트 보여주기 뷰
    #북마크 테이블에서 현재 로그인 사용자에게 콘텐츠 변경이 허용된 객체만 보여주는 뷰
    #Log~~을 상속받으므로 login_required()데코레이터의 영향받음(로그인 한 사람 접근 가능)
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):#현재 로그인된 사용자가 owner로 되어 있는 리스트만 뽑아내 리스트로 보여줌
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):#실제로 바꾸기 할 뷰
    #지정된 레코드 하나를 폼으로 보여주고, 수정된 내용의 유효성 검사 후, 에러없으면 테이블에 추가
    #Log~~을 상속받으므로 login_required()데코레이터의 영향받음(로그인 한 사람 접근 가능)
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')#수정 완료 후 이동할 url

class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    #기존 레코드 중에서 지정된 레코드를 삭제할 것인지 여부를 묻는 싸이트를 보여준다.
    #Log~~을 상속받으므로 login_required()데코레이터의 영향받음(로그인 한 사람 접근 가능)
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

bookmark/templates/bookmark/bookmark_change_list.html
<!--에디트 제네릭뷰도 뷰에서 템플릿 네임을 별도로 지정하지 않으면 정해진 html명이 있다.-->

{% extends 'base.html' %}
<!-- base.html을 상속 받음. 인용부호 필수-->
{% block title%}bookmark_change_List.html{% endblock %}
<!--base에서 블록으로 지정했던 부분만 간단하게 파내서 바꿈-->

{% block content %}
<div id="content">
    <h1>Bookmark change - {{user}}</h1>
    <table class="change-list">
        <tr>
            <th>Title</th>
            <th>Url</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        {% for item in object_list %}
<!--        object_list는 ListView에서 넘겨주는 값-->
        <tr>
            <td>{{item.title}}</td>
            <td>{{item.url}}</td>
            <td>{{item.owner}}</td>
            <td><a href="{% url 'bookmark:update' item.id%}">Update</a></td>
<!--            bookmark/99/update/-->
            <td><a href="{% url 'bookmark:delete' item.id%}">Delete</a></td>
<!--            bookmark/99/delete/-->
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
<!--정말로 지울 것이냐라고 묻는 페이지-->

{% extends 'base.html' %}
<!-- base.html을 상속 받음. 인용부호 필수-->
{% block title%}bookmark_confirm_delete.html{% endblock %}
<!--base에서 블록으로 지정했던 부분만 간단하게 파내서 바꿈-->

{% block content %}
<div id="content">
    <h1>Bookmark Delete</h1>
    <form action="." method="post">{% csrf_token %}
        <p>Are you sure that you want to delete {{ object }}</p>
<!--        object는 delete뷰에서 넘어온 객체 -->
        <input type="submit" value="Confirm">
    </form>
<!--    Confirm버튼을 누르면 이 값을 가지고 DeleteView제네릭 뷰에서 테이블을 지우는 명령을 수행하는 듯-->
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Bookrmark Detail</title>
</head>
<body>
<div id="content">
    <h1>{{object.title}}</h1>
    <!--object는 제네릭뷰에서 자동으로 DB를 조회해 만들어준 변수. 객체의 타이틀명이 표시됨 -->
    <ul>
        <li>URL: <a href="{{object.url}}">{{object.url}}</a></li>
        <!--object의 url의 내용을 가져와서 표시한뒤 링크로 나타내라 -->
    </ul>
</div>
</body>
</html>

bookmark/templates/bookmark/bookmark_detail_alone.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Bookrmark Detail</title>
</head>
<body>
<div id="content">
    <h1>{{object.title}}</h1>
    <!--object는 제네릭뷰에서 자동으로 DB를 조회해 만들어준 변수. 객체의 타이틀명이 표시됨 -->
    <ul>
        <li>URL: <a href="{{object.url}}">{{object.url}}</a></li>
        <!--object의 url의 내용을 가져와서 표시한뒤 링크로 나타내라 -->
    </ul>
</div>
</body>
</html>

bookmark/templates/bookmark/bookmark_form.html
<!--에디트 제네릭뷰도 뷰에서 템플릿 네임을 별도로 지정하지 않으면 정해진 html명이 있다.-->
<!--CreateView와 UpdateView는 모두 모델소문자_form.html로 같은 템플릿명을 사용한다.
view가 달라 처리하는 내용은 다르지만, template가 같으므로 사용자에게 표현하는 형태는 똑같다.-->
{% extends 'base.html' %}
<!-- base.html을 상속 받음. 인용부호 필수-->
{% block title%}bookmark_form.html{% endblock %}
<!--base에서 블록으로 지정했던 부분만 간단하게 파내서 바꿈-->

{% load static %}
{% block extrastyle %}{% static "css/form.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Bookmark Creat/Update - {{user}}</h1>
    <form action="." method="post">{% csrf_token %}
<!--폼 제출시 post방식으로 현재와 같은 url('.')로 요청이 전송됨-->
    {% if form.errors %}
<!--        폼에 입력된 내용에 에러가 있다면. form클래스에 error라는 api가 있음-->
        <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}

    <p>This is a creation or update form for your bookmark.</p>

    <fieldset class="aligned">
<!--    필드셋테그는 폼에서 비슷한 요소들을 그룹으로 묶어주는 역할을 함. 묶은 요소 주변으로 테두리를 그려줌-->
<!--        legend태그를 이용하면 캡션을 추가할 수 있음-->
        <div class="form-row">
            {{form.title.label_tag}} {{form.title}}
<!--    생성/수정처리를 위해 form을 사용(bookmark모델을 사용해 장고가 만듦). view에서 정의한 title필드값이 표시될 것-->
        </div>
        <div class="form-row">
            {{form.url.label_tag}} {{form.url}}
<!--        url입력요소를 출력. form.url은 url필드의 위젯을 출력한다고 함
form의 필드는 각각 특정한 위젯(html에 보여줄 특정형태)으로 매핑되있다고 함. -->
        </div>
    </fieldset>
    <div class="submit-row">
        <input type="submit" value="Submit">
<!--        제출버튼 만들기. 이름은 Submit-->
    </div>
    <script type="text/javascript">document.getElementById('id_title').focus();</script>
<!--자바스크립트로 title입력요소에 커서를 위치시킨다. form.title에서 title이 html상 id로서 처리되는 듯.-->    </form>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Bookmark List BYG</title>
</head>
<body>
<div id="content">
    <h1>Bookmark list</h1>
    <ul>
        {% for bookmark in object_list %}
        <!-- object_list는 제네릭 뷰에서 DB를 조회해 자동으로 만들어서 넘긴 변수명 -->
            <li><a href="{%url 'bookmark:detail' bookmark.id %}">{{bookmark}}</a></li>
<!-- url 2개로 분리전 <li><a href="{%url 'detail' bookmark.id %}">{{bookmark}}</a></li>-->
        <!--url태그 {%url '앱명:패턴name', 변수1, 변수2...%> url패턴에서 url을 추출하는 태그.
         (원래는 {%url 'namespace(:view-name)', 변수1, 변수2...%> view-name대신 패턴이름이 쓰이기도)
         (앱명과 루트urls파일의 해당 앱의 include()-namespace를 같게해야 혼돈되지 않는다. bookmark:detail에서
          bookmark가 앱의 명칭인지, include할때 썻던 namespace의 값인지는 불분명. 후자 같긴 함)
         url을 'bookmark/1/'처럼 하드코딩하지 않고, 'detail'이라는 패턴에서 url스트링을 추출해서 반영.
         urlconf시 name(ex. detail)으로 지정했던 패턴에서 url추출. 링크 클릭시 그 url로 이동하도록.
         변수를 포함해서. 그런데 다른 앱인데도 패턴의 명칭은 똑같을 수 있다. 이를 구분하기 위해 '앱명:패턴명'
         형태로 담아서 호출하기도 한다.-->
        {% endfor %}
    </ul>
</div>
</body>
</html>

bookmark/templates/bookmark/bookmark_list_alone.html
<!--웹서비스 개발시 디자인 변경등의 이유로 프론트엔드 개발이 늦어지기 때문에 백엔드 서비스부터 러프하게 개발해놓고
프론트엔드가 확정되면 이에 맞게 변경한다고 함. 이 템플릿은 백엔드 개발이 정상적으로 동작하는지를 확인하기 위한 것으로
디자인 요소가 전혀 반영되지 않음-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Bookmark List BYG</title>
</head>
<body>
<div id="content">
    <h1>Bookmark list</h1>
    <ul>
        {% for bookmark in object_list %}
        <!-- object_list는 제네릭 뷰에서 DB를 조회해 자동으로 만들어서 넘긴 변수명 -->
            <li><a href="{%url 'bookmark:detail' bookmark.id %}">{{bookmark}}</a></li>
<!-- url 2개로 분리전 <li><a href="%url 'detail' bookmark.id %">bookmark</a></li>-->
        <!--url태그 {%url '앱명:패턴name', 변수1, 변수2...%> url패턴에서 url을 추출하는 태그.
         (원래는 %url 'namespace(:view-name)', 변수1, 변수2...% view-name대신 패턴이름이 쓰이기도)
         (앱명과 루트urls파일의 해당 앱의 include()-namespace를 같게해야 혼돈되지 않는다. bookmark:detail에서
          bookmark가 앱의 명칭인지, include할때 썻던 namespace의 값인지는 불분명. 후자 같긴 함)
         url을 'bookmark/1/'처럼 하드코딩하지 않고, 'detail'이라는 패턴에서 url스트링을 추출해서 반영.
         urlconf시 name(ex. detail)으로 지정했던 패턴에서 url추출. 링크 클릭시 그 url로 이동하도록.
         변수를 포함해서. 그런데 다른 앱인데도 패턴의 명칭은 똑같을 수 있다. 이를 구분하기 위해 '앱명:패턴명'
         형태로 담아서 호출하기도 한다.-->
        {% endfor %}
    </ul>
</div>
</body>
</html>