blog/urls.py
from django.conf.urls import url
from django.urls import path
from blog.views import *
from . import views

app_name = 'blog' #루트 url에서 namespace로 지정한 이름. 꼭 써줘야 defualt url이 됨

urlpatterns =[
    url(r'^$', PostLV.as_view(), name='index'),
    # /. blog/에서 blog는 namespace에서 지정한 부분
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    #위와 동일. 패턴명만 다름
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    #\w는 문자+숫자. '-'가들어간 문자숫자가 하나이상. ex. post/django-example/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    # ex. archive/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    # ex. 2012/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    # ex. 2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(),
        name='post_day_archive'),
    # ex. 2012/nov/10/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    # ex. today/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
    # ex. tag/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    # ex. tag/tagname/
    #[^/]+ : /이외의 문자가 하나이상 있다. (?u)앞의 구문을 유니코드로 인식해라(한글이 와도 인식되도록)
    url(r'^search/$', SearchFormView.as_view(), name='search'),
    #폼을 보여주고 폼에있는 데이터를 처리하기 위해 FormView를 상속받아 정의
    #blog/search/
    path('add/', views.PostCreateView.as_view(), name='add'),  # /Post/add/
    path('change/', views.PostChangeLV.as_view(), name='change'),  # /Post/change/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),  # /Post/99/update/
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),  # /Post/99/delete/
    # url()은 re_url로 대체. views.뷰클래스명.as_view()쓰는 패턴에 유의

]

mainsite/urls.py
# url()와 path()의 차이
# path가 개선된 버전으로 사용 문법이 url에 비해 간략화 됨
# url(r'^book/(?P<pk>/d+)/$', views.book_detail)이
# path(r'^book/<int:pk>/', views.book_detail)로 바뀌어 간단하게 표현할 수 있음

from django.contrib import admin #기본적으로 로딩. admin싸이트 접속용도
from django.urls import path #기본적으로 로딩. path를 통해 보통은 접근
from django.conf.urls import url, include #보통 프로젝트용 url과 앱용 url 두개가 있으나, 여기선 프로젝트용
                                 #하나로만 바로 conf할꺼라 필요

from django.conf.urls.static import static #정적파일을 처리하는 뷰를 호출하도록 그에맞는 url패턴 반환
from django.conf import settings #settings변수 호출. setting.py에서 정의한 객체들을 담고 있음

# from bookmark.views import BookmarkLV, BookmarkDV
#view에서 정의한 클래스뷰들을 불러와서 url로 링크시켜야 해당 요구가 들어왔을때 링크해 줌

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from mainsite.views import HomeView #대문싸이트를 만들기 위한 view
from mainsite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls), #장고 conf파일의 url함수는 내부적으로 re모듈을 호출하는 듯.
                                      #url()의 첫번째 변수가 regex 즉 정규식임
                                      #여기서 바로 정규식을 사용함. ^ ~로 시작하는.

    #인증관련 처리 URL
    url(r'^accounts/', include('django.contrib.auth.urls')),
    #django.co~는 장고가 기본적으로 제공하는 인증관련 앱으로, url과 템플릿파일명이 지정되어 있다. 책236페이지 표 참조
    #로그인/아웃 관련 url과 view는 장고가 제공하나 해당 템플릿은 직접 만들어야 한다. 물론 템플릿명도 지정됨.
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),  #계정 생성처리를 하는 url
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'), #생성 완료를 보여주는 url

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')), #include 함수도 import해야함
    #최근에 url()대신해 path()가 소개됨. 해당 url이 들어오면 bookmark앱의 urls파일로 가서 처리해라
    #차이는 url에서 id를 추출하는 방식이 간편해짐. url은 ?<~~>였는데 path는(<int:number>형식)으로 간단해짐
    url(r'^blog/', include('blog.urls', namespace='blog')), #include 함수도 import해야함
    url(r'^photo/', include('photo.urls', namespace='photo')),
    #url(r'^photo/', ListView.as_view(model=Album), name='album_list'),로 한번에 할 수도 있음

##bookmark를 단독으로 urlconf할때 썻던 코드
    # #Class-based view for bookmark 앱
    # url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),# xx$ xx로 끝나야함
    # #원래는 view.view처리함수 형태가 되어야 하나, 장고의 제네릭(표준)뷰를 쓰기 위해 as_view 사용
    # #name은 이 url패턴을 뭐라고 부를 것인가를 정의하는 것
    # url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
    # #bookmark/11~/형태의 url. ?p<>는 정규식 그룹명을 지정한 것. 뷰를 호출할 때 primary key가
    # #변수로 같이 넘겨짐. views.detal(request, pk)처럼.
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #개발과정에서 미디어파일을 처리하기 위해 추가
#statc(css, js같은 정적인 파일들)파일을 처리하는 url_conf를 추가(왜 쓰는지는 루트폴더에 작성해놓은 '장고 정적서비스 개념잡기 참조'
#static(prefix, view=django.views.static.serve, **kwarg)가 원래 용법
#즉, setting.py에서 MEDIA_URL로 지정한 url('/static/')이 들어오면 django.views.static~~이란
#뷰가 처리하고, 인수로 MEDIA_ROOT(os.path.join(BASE_DIR, 'media'))를 넘겨줘라 라는 것
#view는 장고가 제공하는 view니까 따로 코딩하지 않는 듯.

# static()함수의 다른 설명
# 정적 파일에 접근할 URL 접두사(staticfiles)를 첫 번째 인자로 넣고 정적 파일이 위치한 경로를 document_root라는 키워드 인자로 전달하면,
# 이런 내용을 django.views.static.serve라는 뷰 함수가 사용합니다. 이 serve 함수는 서버에 위치한 파일을 읽어서(open(fullpath, 'rb'))
# 스트리밍 방식으로 응답(StreamingHttpResponse)합니다. 실제 파일 서빙을 하는 것입니다. 물론 성능은 웹 서버가 직접 서빙하는 것보다 떨어지므로
# 개발 단계에서만 쓰는 게 좋을텐데, django.conf.urls.static의 static 함수는 settings의 DEBUG가 True인 경우에만 이런 정적 파일 제공에
# 필요한 URL 패턴을 만듭니다. 간단히 말해서 DEBUG=True인 경우에만 static 함수는 우리가 원하고 기대하는 동작을 합니다.

photo/urls.py
from django.conf.urls import url
from django.urls import path
from photo.views import *
from . import views

app_name = 'photo'

urlpatterns =[
    # ex. '/'
    url(r'^$', AlbumLV.as_view(), name='index'),
    # ex. '/album/'. '/'과 똑같음
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),
    # ex. '/album/99/'
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),
    # ex. '/photo/99/'
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),
    #앨범과 포토를 한번에 처리하는 인라인 모델 폼을 처리하는 뷰. 생성용도.
    # album_form.html에서 처리
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    #바꿀 수 있는 리스트를 단순 표시해주는 뷰
    # album_change_list.html에서 처리
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),
    #앨범과 포토를 한번에 처리하는 인라인 모델 폼을 처리하는 뷰. 변경 용도.
    # album_form.html에서 처리
    path('album/<int:pk>/delete/', views.AlbumDeleteView.as_view(), name='album_delete'),
    # album_confirm_delete.html에서 처리

    path('photo/add/', views.PhotoCreateView.as_view(), name='photo_add'),
    #앨범과 포토를 한번에 처리하는 인라인 모델 폼을 처리하는 뷰. photo_form.html에서 처리
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    #photo_change_list.html에서 처리
    path('photo/<int:pk>/update/', views.PhotoUpdateView.as_view(), name='photo_update'),
    #photo_form.html에서 처리
    path('photo/<int:pk>/delete/', views.PhotoDeleteView.as_view(), name='photo_delete'),
    #photo_confirm_delete.html에서 처리
]

photo/models.py
from __future__ import unicode_literals #python 2.X 호완용
from six import python_2_unicode_compatible #python2.x대의 문자열 처리 방식을 3.x대로 바꿔주는 것
# from django.utils.encoding import python_2_unicode_compatible에서 장고 3.0.4부터 바뀜

from django.db import models
from django.urls import reverse
#from django.core.urlresolvers import reverse #django 2.0 버전에서는 삭제됨
#일반적을 url()은 외부에서 url주소가 주어지면 이를 특정뷰와 연결시켜주는 기능을 한다(path()도 같은 역할)
#(이때 이 패턴에 특정이름을 붙이기도). 반면에 reverse()는 주어진 view로부터 url을 뽑아내는 일을 한다.
#즉 뷰를 실행해 처리결과로 다른 뷰를 로드해야 할때(리다이렉션) reverse를 써서 url을 만든후 다시 연결하는 것.
#그런데 서로다른 앱에서 같은 패턴명을 사용하는 경우도 있다. 이를 구분하기 위해 reverse를 사용할때는
#'앱명:패턴명'을 넣어서 호출하면, 그것에 해당하는 url이 추출되어 장고에 제공된다.
#reverse('blog:post_detail', kwargs={'id':10}) = blog앱의 detail이란 패턴명의 url을 추출하는데
# id값은 10이다. = '/blog/10/'

from photo.fields import ThumbnailImageField
#원본이미지와 썸네일을 모두 저장할 수 있는 커스텀 필드(제공해주는 서드파티가 없으니 직접 제작).

from django.contrib.auth.models import User

@python_2_unicode_compatible
class Album(models.Model):#앨범과 포토의 관계는 1:N관계. 포토에서는 앨범의 Foreign키로 앨범에 대한 소속 구분
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    #사용자만 생성할 수 있도록 소유자필드 추가

    class Meta:#필드속성 외에 필요한 테이블의 파라미터를 정의하기 위해, 내부클래스 선언(이또한 상속받는 것)
        ordering = ['name'] #모델객체의 리스트 출력시 이름순(오름차순)으로 정렬
        #오름차순(ascending)은 순방향(일반적인 사용법 대로. 1-2-3, ㄱ-ㄴ-ㄷ, a-b-c). 오룸-일반(모두 ㅇ)
        #내림차순(descending)은 역방향(일반적인 사용법과 반대)

    def __str__(self):
        return self.name #어디서는 Album테이블의 객체를 호출하면, 그 객체의 name값을 표시하라.
                          #단, __str__을 적용해 문자형태로 알기쉽게 표기

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))
        #photo앱의 album_detail이란 패턴명의 url을 추출해서 반환하는데 변수에는 id값을 넣어라.
        #ex. photo/album/1/

@python_2_unicode_compatible
class Photo(models.Model): #db에는 경로만 저장되고 파일을 media폴더에 저장된다.
    album = models.ForeignKey(Album, on_delete=models.CASCADE) #앨범테이블에 연결된 외래키.
    # 사진이 소속된 앨범객체를 가르킴. 연결된 앨범이 지워지면 photo도 지우라는 옵션(cascade) 추가(필수).
    # django2.0부터는 on_delete옵션을 추가해야함
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    #Thumb~~는 이미지, 썸네일 둘다 저장하는 커스텀 필드(장고가 아니라 서드파티에서 스스로 정의한 필드).
    #모델에서 가져오지 않았음에 주목!! upload_to로 저장할 위치 지정
    #세팅에 MEDIA_ROOT로 지정된 곳 하위에 ~/photo/2020/12처럼 폴더를 만들고 그곳에 사진 및 썸네일 저장
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)
    #auto~~ 객체가 생성될 때 시간을 자동으로 저장. 즉 사진이 업로드 될 때 시간을 자동으로 저장
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    #사용자만 생성할 수 있도록 소유자필드 추가


    class Meta:#필드속성 외에 필요한 테이블의 파라미터를 정의하기 위해, 내부클래스 선언(이또한 상속받는 것)
        ordering = ['title'] #모델객체의 리스트 출력시 이름기준 오름차순으로

    def __str__(self):
        return self.title #어디서는 Photo테이블의 객체를 호출하면, 그 객체의 title값을 표시하라.
                          #단, __str__을 적용해 문자형태로 알기쉽게 표기

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))
        #photo앱의 photo_detail이란 패턴명의 url을 추출해서 반환하는데 변수에는 id값을 넣어라.
        #ex. photo/photo/1/

# 모델을 잡고 나면 앱-admin파일로 가서 이 모델이 admin사이트에서 어떻게 보일지를 세팅해줘야 함

photo/forms.py
#폼셋이란 동일한 폼 여러개로 구성된 폼을 지칭. 또 인라인 폼셋이란 메인 폼에 딸려있는 하위 폼셋을 지칭
#테이블의 관계가 1:N일 경우, N테이블의 레코드 여러개를 동시에 입력받기 위한 용도로 인라인폼셋 사용.

from photo.models import Album, Photo
from django.forms.models import inlineformset_factory#인라인 폼셋을 만들어주는 메소드

PhotoInlineFormSet = inlineformset_factory(Album, Photo,
                    fields=['image', 'title', 'description'], extra=2)
#1:N에서 Album이 1, Photo가 N임을 지정. 폼셋에 사용할 필드를 지정하고, 빈폼 개수는 2개로 지정

photo/templates/photo/album_change_list.html
<!--에디트 제네릭뷰도 뷰에서 템플릿 네임을 별도로 지정하지 않으면 정해진 html명이 있다.-->
<!--CreateView와 UpdateView는 모두 모델소문자_form.html로 같은 템플릿명을 사용한다.
view가 달라 처리하는 내용은 다르지만, template가 같으므로 사용자에게 표현하는 형태는 똑같다.-->
{% extends 'base.html' %}
<!-- base.html을 상속 받음. 인용부호 필수-->
{% block title%}album_change_list.html{% endblock %}
<!--base에서 블록으로 지정했던 부분만 간단하게 파내서 바꿈-->

{% load static %}
{% block extrastyle %}{% static "css/form.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Album change - {{user}}</h1>
    <table class="change-list">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        {% for item in object_list %}
<!--        object_list는 ListView에서 넘겨주는 값-->
        <tr>
            <td>{{item.Name}}</td>
            <td>{{item.description}}</td>
            <td>{{item.owner}}</td>
            <td><a href="{% url 'photo:album_update' item.id%}">Update</a></td>
<!--            photo/99/update/-->
            <td><a href="{% url 'photo:album_delete' item.id%}">Delete</a></td>
<!--            photo/99/delete/-->
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

photo/templates/photo/album_confirm_delete.html
<!--정말로 지울 것이냐라고 묻는 페이지-->

{% extends 'base.html' %}
<!-- base.html을 상속 받음. 인용부호 필수-->
{% block title%}Album_confirm_delete.html{% endblock %}
<!--base에서 블록으로 지정했던 부분만 간단하게 파내서 바꿈-->

{% block content %}
<div id="content">
    <h1>Album Delete</h1>
    <form action="." method="post">{% csrf_token %}
        <p>Are you sure that you want to delete {{ object }}</p>
<!--        object는 delete뷰에서 넘어온 객체 -->
        <input type="submit" value="Confirm">
    </form>
<!--    Confirm버튼을 누르면 이 값을 가지고 DeleteView제네릭 뷰에서 테이블을 지우는 명령을 수행하는 듯-->
</div>
{% endblock %}

photo/templates/photo/album_detail.html
{% extends 'base.html' %}
<!-- base.html을 상속 받음. 인용부호 필수-->
{% block title%}album_detail.html{% endblock %}
<!--base에서 블록으로 지정했던 부분만 간단하게 파내서 바꿈-->

{% load static %} {# static태그를 쓰기 위해 #}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}
<!-- static태그는 정적파일의 절대url을 생성, 링크로 쓸 수 있게 해줌-->
{% block content %}
<div id="content">
<!--    특정 앨범에 들어있는 사진을 모두 나타내기-->
    <h2 style="diplay:inline;">{{object.name}}</h2>
    &emps;<b><i>{{object.description}}</i></b>
    <hr/>
    <div class="album-detail">
        {% for photo in object.photo_set.all %}
<!--        1:N설정시 N에해당하는 모델은 모델명소문자_set으로 소속된 N개의 요소를 불러올 수 있는 듯.
question과 choice의 관계에서도 qusetion의 object에 소속된 choice를 템블릿에서 부를 때,
object.choice_set.all로 불렀었음-->
            <div class="album-detail-photo">
                <a href="{{photo.get_absolute_url}}">
                    <img class="thumbnail" src="{{photo.image.thumb_url}}"/>
 <!--            photo테이블의 image라는 칼럼은 thumbnailImageField가 처리하므로
field.py의 thumb~~클래스에서 property로 속성화했던 thumb_url은 image.thumb_url을 통해 get함수를
호출할 수 있게 됨. 즉 _get_thumb_url함수를 호출, url을 받아온다. 결과적으로 받아온 url를 소스로 해서
이미지를 불러들인다.-->
                </a>
                <li>{{photo.title}}</li>
                <li>{{photo.upload_date|date:"Y-m-d"}}</li>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

photo/templates/photo/album_list.html
{% extends 'base.html' %}
<!-- base.html을 상속 받음. 인용부호 필수-->
{% block title%}album_list.html{% endblock %}
<!--base에서 블록으로 지정했던 부분만 간단하게 파내서 바꿈-->

{% load static %} {# static태그를 쓰기 위해 #}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}
<!-- static태그는 정적파일의 절대url을 생성, 링크로 쓸 수 있게 해줌-->
{% block content %}
<div id="content">
<!--    앨범당 사진 5개씩 띄워서 보여주는 html작성-->
    {% for item in object_list %}
        <div class="clear_float">
            <h2 style="display:inline;"><a href="{% url 'photo:album_detail' item.id %}">
                {{ item.name }}</a> </h2>
            &amp;<b><i>{{ item.description }}</i></b>
        </div>
    <hr/>
    <div class="album-list">
        {% for photo in item.photo_set.all|slice:":5" %}
<!--    해당 앨범에 연결 된 사진객체를 앞에서부터 5개 보여줘라. photo_set이란 ORM명령이 있음-->
        <div class="album-list-photo">
            <a href="{{photo.get_absolute_url}}">
                <img class="thumbnail" src="{{photo.image.thumb_url}}"/>
<!--            썸네일을 띄우되 클릭하면 상세설정으로 들어가도록 썸네일을 링크화 한다.-->
<!--            album에 photo가 묶여있고 photo테이블의 image라는 칼럼은 thumbnailImageField가 처리하므로
field.py의 thumb~~클래스에서 property로 속성화했던 thumb_url은 image.thumb_url을 통해 get함수를
호출할 수 있게 됨. 즉 _get_thumb_url함수를 호출, url을 받아온다. 결과적으로 받아온 url를 소스로 해서
이미지를 불러들인다.-->
            </a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

photo/templates/photo/photo_change_list.html
<!--에디트 제네릭뷰도 뷰에서 템플릿 네임을 별도로 지정하지 않으면 정해진 html명이 있다.-->
<!--CreateView와 UpdateView는 모두 모델소문자_form.html로 같은 템플릿명을 사용한다.
view가 달라 처리하는 내용은 다르지만, template가 같으므로 사용자에게 표현하는 형태는 똑같다.-->
{% extends 'base.html' %}
<!-- base.html을 상속 받음. 인용부호 필수-->
{% block title%}photo_change_list.html{% endblock %}
<!--base에서 블록으로 지정했던 부분만 간단하게 파내서 바꿈-->

{% load static %}
{% block extrastyle %}{% static "css/form.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Photo change - {{user}}</h1>
    <table class="change-list">
        <tr>
            <th>Album</th>
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        {% for item in object_list %}
<!--        object_list는 ListView에서 넘겨주는 값-->
        <tr>
            <td>{{item.album}}</td>
            <td>{{item.title}}</td>
            <td>{{item.description|linebreaks}}</td>
            <td>{{item.owner}}</td>
            <td><a href="{% url 'photo:photo_update' item.id%}">Update</a></td>
<!--            photo/99/update/-->
            <td><a href="{% url 'photo:photo_delete' item.id%}">Delete</a></td>
<!--            photo/99/delete/-->
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

photo/templates/photo/photo_confirm_delete.html
<!--정말로 지울 것이냐라고 묻는 페이지-->

{% extends 'base.html' %}
<!-- base.html을 상속 받음. 인용부호 필수-->
{% block title%}Photo_confirm_delete.html{% endblock %}
<!--base에서 블록으로 지정했던 부분만 간단하게 파내서 바꿈-->

{% block content %}
<div id="content">
    <h1>Photo Delete</h1>
    <form action="." method="post">{% csrf_token %}
        <p>Are you sure that you want to delete {{ object }}</p>
<!--        object는 delete뷰에서 넘어온 객체 -->
        <input type="submit" value="Confirm">
    </form>
<!--    Confirm버튼을 누르면 이 값을 가지고 DeleteView제네릭 뷰에서 테이블을 지우는 명령을 수행하는 듯-->
</div>
{% endblock %}

photo/templates/photo/photo_form.html
<!--에디트 제네릭뷰도 뷰에서 템플릿 네임을 별도로 지정하지 않으면 정해진 html명이 있다.-->
<!--CreateView와 UpdateView는 모두 모델소문자_form.html로 같은 템플릿명을 사용한다.
view가 달라 처리하는 내용은 다르지만, template가 같으므로 사용자에게 표현하는 형태는 똑같다.-->
{% extends 'base.html' %}
<!-- base.html을 상속 받음. 인용부호 필수-->
{% block title%}Photo_form.html{% endblock %}
<!--base에서 블록으로 지정했던 부분만 간단하게 파내서 바꿈-->

{% load static %}
{% block extrastyle %}{% static "css/form.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Photo Creat/Update - {{user}}</h1>
    {% if form.is_multipart %}
        <form enctype="multipart/form-data" action="." method="post">{% csrf_token %}
<!--파일을 업로드할 경우 enctype을 multipart~~로 지정해야 함-->
    {% else %}
        <form method="post" action=".">
<!--폼 제출시 post방식으로 현재와 같은 url('.')로 요청이 전송됨-->
    {% endif %}{% csrf_token %}

    {% if form.errors %}
<!--        폼에 입력된 내용에 에러가 있다면. form클래스에 error라는 api가 있음-->
        <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}

    <p>This is a creation or update form for your photo.</p>

    <fieldset class="aligned">
<!--    필드셋테그는 폼에서 비슷한 요소들을 그룹으로 묶어주는 역할을 함. 묶은 요소 주변으로 테두리를 그려줌-->
<!--        legend태그를 이용하면 캡션을 추가할 수 있음-->
        <div class="form-row">
            {{form.image.label_tag}} {{form.image}}
        </div>
        <div class="form-row">
            {{form.album.label_tag}} {{form.album}}
<!--        앨범을 선택하는 드롭다운 박스 위젯이 출력됨. 1:N의 관계라 photo에서도 album을 선택할 수 있도록 해줌 -->
            <button type="button"><a href="{% url 'photo:album_add' %}">Add Album</a> </button>
        </div>
        <div class="form-row">
            {{form.title.label_tag}} {{form.title}}
        </div>
        <div class="form-row">
            {{form.description.label_tag}} {{form.description}}
        </div>
    </fieldset>
    <div class="submit-row">
        <input type="submit" value="Submit">
<!--        제출버튼 만들기. 이름은 Submit-->
    </div>
    <script type="text/javascript">document.getElementById('id_title').focus();</script>
<!--자바스크립트로 title입력요소에 커서를 위치시킨다. form.title에서 title이 html상 id로서 처리되는 듯.-->
    </form>
</div>
{% endblock %}