blog/urls.py
from django.conf.urls import url
from django.urls import path
from blog.views import *
from . import views

app_name = 'blog' #루트 url에서 namespace로 지정한 이름. 꼭 써줘야 defualt url이 됨

urlpatterns =[
    url(r'^$', PostLV.as_view(), name='index'),
    # /. blog/에서 blog는 namespace에서 지정한 부분
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    #위와 동일. 패턴명만 다름
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    #\w는 문자+숫자. '-'가들어간 문자숫자가 하나이상. ex. post/django-example/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    # ex. archive/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    # ex. 2012/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    # ex. 2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(),
        name='post_day_archive'),
    # ex. 2012/nov/10/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    # ex. today/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
    # ex. tag/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    # ex. tag/tagname/
    #[^/]+ : /이외의 문자가 하나이상 있다. (?u)앞의 구문을 유니코드로 인식해라(한글이 와도 인식되도록)
    url(r'^search/$', SearchFormView.as_view(), name='search'),
    #폼을 보여주고 폼에있는 데이터를 처리하기 위해 FormView를 상속받아 정의
    #blog/search/
    path('add/', views.PostCreateView.as_view(), name='add'),  # /Post/add/
    path('change/', views.PostChangeLV.as_view(), name='change'),  # /Post/change/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),  # /Post/99/update/
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),  # /Post/99/delete/
    # url()은 re_url로 대체. views.뷰클래스명.as_view()쓰는 패턴에 유의

]

mainsite/urls.py
# url()와 path()의 차이
# path가 개선된 버전으로 사용 문법이 url에 비해 간략화 됨
# url(r'^book/(?P<pk>/d+)/$', views.book_detail)이
# path(r'^book/<int:pk>/', views.book_detail)로 바뀌어 간단하게 표현할 수 있음

from django.contrib import admin #기본적으로 로딩. admin싸이트 접속용도
from django.urls import path #기본적으로 로딩. path를 통해 보통은 접근
from django.conf.urls import url, include #보통 프로젝트용 url과 앱용 url 두개가 있으나, 여기선 프로젝트용
                                 #하나로만 바로 conf할꺼라 필요

from django.conf.urls.static import static #정적파일을 처리하는 뷰를 호출하도록 그에맞는 url패턴 반환
from django.conf import settings #settings변수 호출. setting.py에서 정의한 객체들을 담고 있음

# from bookmark.views import BookmarkLV, BookmarkDV
#view에서 정의한 클래스뷰들을 불러와서 url로 링크시켜야 해당 요구가 들어왔을때 링크해 줌

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from mainsite.views import HomeView #대문싸이트를 만들기 위한 view
from mainsite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls), #장고 conf파일의 url함수는 내부적으로 re모듈을 호출하는 듯.
                                      #url()의 첫번째 변수가 regex 즉 정규식임
                                      #여기서 바로 정규식을 사용함. ^ ~로 시작하는.

    #인증관련 처리 URL
    url(r'^accounts/', include('django.contrib.auth.urls')),
    #django.co~는 장고가 기본적으로 제공하는 인증관련 앱으로, url과 템플릿파일명이 지정되어 있다. 책236페이지 표 참조
    #로그인/아웃 관련 url과 view는 장고가 제공하나 해당 템플릿은 직접 만들어야 한다. 물론 템플릿명도 지정됨.
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),  #계정 생성처리를 하는 url
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'), #생성 완료를 보여주는 url

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')), #include 함수도 import해야함
    #최근에 url()대신해 path()가 소개됨. 해당 url이 들어오면 bookmark앱의 urls파일로 가서 처리해라
    #차이는 url에서 id를 추출하는 방식이 간편해짐. url은 ?<~~>였는데 path는(<int:number>형식)으로 간단해짐
    url(r'^blog/', include('blog.urls', namespace='blog')), #include 함수도 import해야함
    url(r'^photo/', include('photo.urls', namespace='photo')),
    #url(r'^photo/', ListView.as_view(model=Album), name='album_list'),로 한번에 할 수도 있음

##bookmark를 단독으로 urlconf할때 썻던 코드
    # #Class-based view for bookmark 앱
    # url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),# xx$ xx로 끝나야함
    # #원래는 view.view처리함수 형태가 되어야 하나, 장고의 제네릭(표준)뷰를 쓰기 위해 as_view 사용
    # #name은 이 url패턴을 뭐라고 부를 것인가를 정의하는 것
    # url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
    # #bookmark/11~/형태의 url. ?p<>는 정규식 그룹명을 지정한 것. 뷰를 호출할 때 primary key가
    # #변수로 같이 넘겨짐. views.detal(request, pk)처럼.
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #개발과정에서 미디어파일을 처리하기 위해 추가
#statc(css, js같은 정적인 파일들)파일을 처리하는 url_conf를 추가(왜 쓰는지는 루트폴더에 작성해놓은 '장고 정적서비스 개념잡기 참조'
#static(prefix, view=django.views.static.serve, **kwarg)가 원래 용법
#즉, setting.py에서 MEDIA_URL로 지정한 url('/static/')이 들어오면 django.views.static~~이란
#뷰가 처리하고, 인수로 MEDIA_ROOT(os.path.join(BASE_DIR, 'media'))를 넘겨줘라 라는 것
#view는 장고가 제공하는 view니까 따로 코딩하지 않는 듯.

# static()함수의 다른 설명
# 정적 파일에 접근할 URL 접두사(staticfiles)를 첫 번째 인자로 넣고 정적 파일이 위치한 경로를 document_root라는 키워드 인자로 전달하면,
# 이런 내용을 django.views.static.serve라는 뷰 함수가 사용합니다. 이 serve 함수는 서버에 위치한 파일을 읽어서(open(fullpath, 'rb'))
# 스트리밍 방식으로 응답(StreamingHttpResponse)합니다. 실제 파일 서빙을 하는 것입니다. 물론 성능은 웹 서버가 직접 서빙하는 것보다 떨어지므로
# 개발 단계에서만 쓰는 게 좋을텐데, django.conf.urls.static의 static 함수는 settings의 DEBUG가 True인 경우에만 이런 정적 파일 제공에
# 필요한 URL 패턴을 만듭니다. 간단히 말해서 DEBUG=True인 경우에만 static 함수는 우리가 원하고 기대하는 동작을 합니다.

photo/urls.py
from django.conf.urls import url
from django.urls import path
from photo.views import *
from . import views

app_name = 'photo'

urlpatterns =[
    # ex. '/'
    url(r'^$', AlbumLV.as_view(), name='index'),
    # ex. '/album/'. '/'과 똑같음
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),
    # ex. '/album/99/'
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),
    # ex. '/photo/99/'
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),
    #앨범과 포토를 한번에 처리하는 인라인 모델 폼을 처리하는 뷰. 생성용도.
    # album_form.html에서 처리
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    #바꿀 수 있는 리스트를 단순 표시해주는 뷰
    # album_change_list.html에서 처리
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),
    #앨범과 포토를 한번에 처리하는 인라인 모델 폼을 처리하는 뷰. 변경 용도.
    # album_form.html에서 처리
    path('album/<int:pk>/delete/', views.AlbumDeleteView.as_view(), name='album_delete'),
    # album_confirm_delete.html에서 처리

    path('photo/add/', views.PhotoCreateView.as_view(), name='photo_add'),
    #앨범과 포토를 한번에 처리하는 인라인 모델 폼을 처리하는 뷰. photo_form.html에서 처리
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    #photo_change_list.html에서 처리
    path('photo/<int:pk>/update/', views.PhotoUpdateView.as_view(), name='photo_update'),
    #photo_form.html에서 처리
    path('photo/<int:pk>/delete/', views.PhotoDeleteView.as_view(), name='photo_delete'),
    #photo_confirm_delete.html에서 처리
]

templates/base.html
<!--base.html로 사이트 전체의 Look&feel을 정하고 다른 곳에선
이를 extends로 상속받아 활용하면 일관성있는 프론트엔드 제작 가능-->
<!DOCTYPE html>
<!--HTML5 준수: html의 업그레이드 버전으로 플러그인 없이 다양한 웹서비스를 가능하게 해주는 언어-->
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django Web Programming{% endblock %}</title>
    {#블록으로 지정된 부분을 extends로 확장해서 쓸 수 있음#}
    {#title, extrastyle, content, footer 총 4개의 block을 미리 지정해둠#}
    {% load static %}
{# static파일이란 img, css, 자바스크립트처럼 응답할때 별도의 처리없이 그대로 보내주면 되는 파일들 #}
<!--장고에서는 이미지나 업로드한 파일들은 MEDIA로, CSS나 JS파일들은 STATIC으로 따로 분류.-->
    <!-- static태그를 쓰려면 staticfile을 로드해야함(지금은 %load static%으로 바뀜)-->
    <!--%static%태그는 정적파일의 절대 url을 생성, 링크로 쓸 수 있게 함 -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}"/>
<!--외부에서 불러올 문서는 스타일시트고 타입은 css, 링크는 '특정경로'다. -->
<!--특정경로는 setting.py에서 static파일의 위치로 지정해둔 위치가 됨. -->
<!--추가로 불러쓸 정적파일의 자리를 미리 만들어 줌-->
</head>
<body>
<div id="header">
    <a href="{% url 'home' %}"><h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2></a>
    {% if user.is_active %}
<!--  django.user.auth앱이 등록되어 있으면 자동으로 User라는 Model을 사용할 수 있는 것으로 추정.
처음 admin싸이트를 열었을 때 나타나있은 user모델이 이에 해당하는 듯.
user모델은 is_active, get_short_name, get_username같은 컬럼을 가지고 있으므로 불러쓸 수 있다.-->
<!--  user는 장고의 기본 템플릿 변수. 모든 템플릿파일에서 사용 가능. is_active()는 로그인시 True반환 -->
    <h4 class="welcome">Welcome,
        <strong>{% firstof user.get_short_name user.get_username%}</strong> /
<!--firstof 태그는 뒤에오는 값 중 False가 아닌 첫 인자를 선택. 예제에서 short_name(first_name)은
 공백이므로 username이 오게 될 것-->
        <a href="{% url 'password_change' %}">Change Password</a> /
        <a href="{% url 'logout' %}">logout</a>
    </h4>
    {% else %}
<!--    로그인 상태가 아닐때 표시할 창-->
    <h4 class="welcome">Welcome, Anonymous /
        <a href="{% url 'login' %}">Login</a> /
        <a href="{% url 'register' %}">Register</a>
    </h4>
    {% endif %}
</div>
<!--body의 헤더 부분. -->
<!-- href='#'은 추후에 링크로 채워질 부분. 의미없는 링크를 집어넣어 화면에 링크만 표시되게 내놓음-->

<div id="menu">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
    <li><a href="{% url 'blog:index' %}">Blog</a></li>
    <li><a href="{% url 'photo:index' %}">Photo</a></li>
<!--메뉴부분에 나타날 앱이동 메뉴-->
    <li><a href="#">Add&bigtriangledown;</a>
        <ul>
            <li><a href="{% url 'bookmark:add' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:add' %}">Post</a></li>
            <li><a href="{% url 'photo:album_add' %}">Album</a></li>
            <li><a href="{% url 'photo:photo_add' %}">Photo</a></li>
        </ul>
    </li>
    <li><a href="#">Change&bigtriangledown;</a>
        <ul>
            <li><a href="{% url 'bookmark:change' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:change' %}">Post</a></li>
            <li><a href="{% url 'photo:album_change' %}">Album</a></li>
            <li><a href="{% url 'photo:photo_change' %}">Photo</a></li>
        </ul>
    </li>
<!--각앱의 추가 변경화면으로 이동할 링크-->
    <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
    <li><a href="{% url 'blog:search' %}">Search</a></li>
    <li><a href="{% url 'admin:index' %}">Admin</a></li>
<!--아카이브, 찾기, 관리자 링크 표시-->
</div>
{% block content %}{% endblock %}
<!--각 하위 탬플릿에서 채워갈 내용 부분-->
{% block footer %}{% endblock %}
<!--각 하위 템플릿에서 채워갈 풋터 부분-->
</body>
</html>

templates/home.html
{% extends 'base.html' %}
<!-- base.html을 상속 받음. 인용부호 필수-->
{% block title%}home.html{% endblock %}
<!--base에서 블록으로 지정했던 부분만 간단하게 파내서 바꿈-->
{% load static %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}
<div id="content_home">
    <div id="homeimg">
        <a href="#"><img src="{% static 'img/django-actor-big.jpg' %}" style="height:256px;"/></a>
<!--        이미지 위에 마우스를 올렸을 때 화살표가 손모양으로 바뀌도록(링크니까) 가짜 링크를 걸어주는 방식. 실무에서 흔히 사용-->
<!--        이미지 태그 마지막의 '/'는 단독 태그 사용시 마지막을 알리는 표시. html5에서는 안써도 됨 -->
        <h4 style="margin:0;">This is Django Powered Web Site.</h4>
    </div>

    <hr style="margin: 5px 0;">
<!--    hr태그는 수평선 긋기. html5에서는 의미적으로 구분하는 용도로 많이 쓰인다고 함. 닫는태그 없음-->
<!--    마진영역에 상하는 5px, 좌우는 0px을 지정-->

    <h2>Select Application</h2>
    <table id="applist">
        <tr>
            <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i></b></td>
            <td>You can write your own post and share to others. I stronglly recomend you to
            use another tools like the bootstrap for making front end rather than to code by yourself</td>
            <td class="Edit"><i><a href="{% url 'bookmark:add' %}">Add</a></i></td>
            <td class="Edit"><i><a href="{% url 'bookmark:change' %}">Change</a></i></td>
        </tr>

        <tr>
            <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i></b></td>
            <td>You can write your own post and share to others. I stronglly recomend you to
            use another tools like the bootstrap for making front end rather than to code by yourself</td>
            <td class="Edit"><i><a href="{% url 'blog:add' %}">Add</a></i></td>
            <td class="Edit"><i><a href="{% url 'blog:change' %}">Change</a></i></td>
        </tr>

        <tr>
            <td><b><i><a href="{% url 'photo:index' %}">Photo</a></i></b></td>
            <td>You can write your own post and share to others. I stronglly recomend you to
            use another tools like the bootstrap for making front end rather than to code by yourself</td>
            <td class="Edit"><i><a href="{% url 'photo:album_add' %}">Add</a></i></td>
            <td class="Edit"><i><a href="{% url 'photo:album_change' %}">Change</a></i></td>
        </tr>
    </table>
</div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; TGK 2020
<!--    &copy;는 저작권표시하는 특수 문자-->
</div>
{% endblock %}